### ISSUE TITLE
Android Gradle build 

### ISSUE THREAD

**Issue by va1046** [cloudant/sync-android#209]
I have tried number of ways to use the sync-android repo and i'm totally confused how to use this repo in my app. Can anyone guide me .. so i could start working on this soon.

**Comment by rhyshort** [comment]
If you add `compile group: 'com.cloudant', name: 'cloudant-sync-datastore-android', version:'0.13.4'` to your `dependancies` block and `maven { url "http://cloudant.github.io/cloudant-sync-eap/repository/" }` to your repository blocks of your gradle file. You'll be able to use sync-android in your android app

**Comment by va1046** [comment]
Thanks @rhyshort i could use sync-android.

**Comment by rhyshort** [comment]
Great :)

**Comment by va1046** [comment]
Hi Rhyshort I was trying to debug the todosync sample app provided by you guys. I want to make a bridge call to DreamFactory which is my middle ware between my client and server. I want to make cloud sync Push service from a API to push the data to my cloudant DB.  Let me explain you my architecture 

 || {My DB} **Cloudant** || <===> || *{My REST API service}* **DreamFactory** || <===> || *{Call the Dreamfactory API's for Read/Write on Cloudant}* **Android** ||

Can i make a API call to replicate the data into my DB. I tried to make a URL call to replicate but it is an error (java.net.URL) cannot be applied to ReplicateBuilder.

**Comment by rhyshort** [comment]
@va1046 the `ReplicatorBuilder` should be able to take a remote URL for the `from` method with a `pull` replication and a for the `to` method for a push replication. Assuming your API service has all the APIs required to perform the replication it should work.

**Comment by va1046** [comment]
@rhyshort I have to call API's using HTTP Request Methods (Get,Post) in a URI call to the API i could send the following request and My session is being handled by DreamFactory and I couldn't Write on the Cloudant DB unless i have a proper session created to make the calls. Can you let me know  how to make these calls.

**Comment by rhyshort** [comment]
What request? We don't support making requests to APIs that aren't CouchDB compatible.

**Comment by va1046** [comment]
@rhyshort As i told you my architecture that I Configured 
**Cloudant CouchDB ** through ** DreamFactory** and made API avaiable to Client side.
Session management i handled by DF to do any operations on Cloudant DB a User should login and then he will be given a session to do operations on the Cloudant DB.

**Comment by mikerhodes** [comment]
@va1046 As far as I can see, DreamFactory doesn't proxy through the CouchDB HTTP API but instead provides its own data access HTTP API (from [their blog on NoSQL support](http://blog.dreamfactory.com/blog/bid/326725/NoSQL-No-Problem)).

Sync-Android doesn't support access through the DreamFactory API. If you want to use Sync-Android you'll need to provide it with a URL that points to something which supports the CouchDB HTTP API (e.g., if DreamFactory offers a simple proxy mechanism rather than providing its own API).

**Comment by va1046** [comment]
@mikerhodes Thanks for sharing the article. I again went through your TODO sync sample app. Whenever i'm trying push the data using the **replicationbuilder** i have to call a URI and not a API URL. With out a Request method how could I replicate the local data to remote database. I'm trying to figure out the possibility to use this Cloud Sync from the Client point of View.  

**As an Example:**
1. To **Write** something into my database. I'm calling the **REST API** link using a **HTTP method** i.e., **POST** method.
2. To **Read** something from my database. I'm calling the **REST API** link using a **HTTP method** i.e., **GET** method.

In the same way when i'm trying to push the data from Local instance to Remote DB using replicationbuilder there is no proper call to the DB through Dreamfactory. If the call is not going through DreamFactory I have to face security issues like no session management and my  DB is open to all.

**Comment by mikerhodes** [comment]
@va1046 Sync-Android is unable to replicate data through the APIs that DreamFactory provides. 

If you want to use Sync-Android, it looks like you'll need something to replace DreamFactory as your API management layer -- you'll need to find something which will act as a proxy to the CouchDB API rather than introduce its own, different way to interact with the data in CouchDB.
