### ISSUE TITLE
Empty Datastore

### ISSUE THREAD

**Issue by segunmicheal27** [cloudant/sync-android#243]
I keep getting this error every time i try to fetch data from Data store please help
I/DatastoreManager: dbDirectory: /data/user/0/com.example.michaelwizard.coudapp/app_data/datastores
03-13 14:18:28.652 3925-3925/com.example.hello.coudapp I/DatastoreManager: dbDirectoryExist: true
03-13 14:18:29.747 3925-3925/com.example.hello.coudapp W/QueryExecutor: Projection fields array is empty, disabling project for this query

**Comment by rhyshort** [comment]
The log messages are harmless, they aid us debugging the library when an issue is raised. The first message indicates that the database directory exists, which is good, it means we can write the information we need to. The second message indicates that you have called either
```
IndexManager#find(Map<String, Object> query)
``` 
or 
```
IndexManager#find(Map<String, Object> query,
                            long skip,
                            long limit,
                            List<String> fields,
                            List<Map<String, String>> sortDocument)
 ``` 
with either a `fields` equal to `null` or is empty. 

Doing so turns off a query feature known as projection, which is where we return a document with only the fields asked for in the fields list if present. 

I think that specific log message should be lowered to info since it is likely that you didn't want to use the projection feature of query. 

I hope this explains why you are seeing those messages in your logs.

**Comment by segunmicheal27** [comment]
yeah i have really figure out what problem is, the reason why i am seeing the error is because the index has not yet created in the data-store at first place but when i run it second time it return the index already exits by Sqlite error

**Comment by segunmicheal27** [comment]
but here is my notice, if i use my index this way: {field name,field column},"index name","index type"

the index create successfully in data-store, though i am using android studio

**Comment by rhyshort** [comment]
hmmm I think this is related to #246 the `indexType`, if you change `"index type"` to `"json"` does it work as expected? You may need to clear out the Query database on the device for it to work though

**Comment by segunmicheal27** [comment]
The problem is fix by aplying the projection field 
```
List<String> fields = Arrays.asList("name", "age", "data","year"); 
        QueryResult result = indexManager.find(query, 0, 0, fields, null);
```
