### ISSUE TITLE
Move IndexManager public API to Datastore

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#284]
The IndexManager lifecycle is tied to that of a Datastore because it cannot exist without it. We should cement that relationship by moving the public methods from IndexManager to Datastore. This will also make the query experience on Android and iOS more consistent.

~~1.  Mark IndexManager as not API (this could be a major version change if for example making IndexManager a default visibility class, so will need some careful thought around deprecation or using the not API tags and backwards compatibility)
2.  Add a DatastoreIndexManager interface containing the public methods in the IndexManager
3.  DatastoreImpl to implement Datastore and DatastoreIndexManager
4. Close IndexManager when the datastore is closed~~

(See edit below)

**Comment by tomblench** [comment]
Feature branch: `feature-284-refactor-datastore-indexmanager`

Inspired by the ideas above, the current thinking we've arrived as is:

- Changes will introduce breaking changes and necessitate major version increment to 2.
- Introduce a new class - `CloudantSync`, with overall lifecycle responsibility for CRUD (`Database`) and `IndexManager` objects. These names are still _definitely_ up for debate. Specifically `CloudantSync` could be confusing because it doesn't suggest that the data is 'local'. Also `Database` and `IndexManager` are inconsistent in that one has "Manager" in the name and one doesn't.
- Close `IndexManager` when `Database` is closed. Achieved by adding `close()` to `CloudantSync` class and removing public close methods for the classes it manages (so you can't close one without closing the other).
- Enable "purge" feature by `IndexManager` subscribing to `DocumentPurged` events from `Datastore`. Would allow implementation of #160 
- Use breaking API change as an opportunity to address indexing code shortcomings including #305 #366. This would tidy up method signatures and add `throws` clauses to allow checked exceptions to be thrown.

**Comment by ricellis** [comment]
@tomblench can this close now?

**Comment by tomblench** [comment]
@ricellis yes I think we've done everything now - this issue covers what became the `DocumentStore` class which manages `Database` and `Query` lifecycle in tandem.

**Comment by ricellis** [comment]
Fixed by the merge of v2 stuff #501
