### ISSUE TITLE
Sample app todo-sync does not build, refers to unreleased api

### ISSUE THREAD

**Issue by mtotschnig** [cloudant/sync-android#295]
Build of sample app fails with
/.../sync-android/sample/todo-sync/src/com/cloudant/todo/TasksModel.java
Error:(73, 52) error: cannot find symbol method getInstance(String)
Also after switching to  version:'latest.integration'

**Comment by mtotschnig** [comment]
I overlooked that when switching to integration, you also have to also add Sonatype repository. With this I can run the sample app. But still for new users it would be better, if it were in sync with the final releases and would run without editing build file.

**Comment by ricellis** [comment]
The `master` branch of our repository is always the unreleased version.

If you checkout the `1.0.0` tag to get the last released sample app it will build with no changes as the sample app dependency is pointing at `cloudant-sync-datastore-android` 'latest.release': https://github.com/cloudant/sync-android/blob/1.0.0/sample/todo-sync/build.gradle#L21.

If you are using the sample app on the `master` branch, then you are correct it is currently not compatible with the `latest.release` version because it has been updated to use the unreleased APIs. You are also correct that changing the sample's `cloudant-sync-datastore-android` dependency to `latest.integration` at https://github.com/cloudant/sync-android/blob/master/sample/todo-sync/build.gradle#L21 will work as long as you also have a repository with an integration build of the master branch (sonatype or local).

I think the fact that our master branch does not reflect our latest release is confusing for a lot of users and we should either change our dev process to develop the next release on a branch that merges alter or update our sample documentation to tell people to checkout the last release tag before building to avoid this type of problem.

**Comment by tomblench** [comment]
Note that our git tags get automatically turned into releases on github: https://github.com/cloudant/sync-android/releases

I don't understand how to mark a release as 'latest' but I have seen this functionality on other projects. It's then possible to go to `releases/latest` but unfortunately there doesn't seem to be any way of doing this for `blob` links - latest is a simple redirect to r`eleases/tag/blah`

**Comment by tomblench** [comment]
Another idea is to create and destroy a 'symbolic link' tag each time we do a release which has a special name like `latest-release`. This would always be guaranteed to point to the last released version. We can then have a banner at the top of READMEs directing users to this version.

**Comment by tomblench** [comment]
Also note that we should make all of our `blob` links relative otherwise they cross-document links will take the user back do `master`

**Comment by tomblench** [comment]
Suggestion for `README`s: prominent banner saying "this is a pre-release version" followed by links to the lastest _n_ release tags in github, plus a link to the full list of release tags. The banner should be prominent and encourage the user to browse the documentation/sample for the latest release.

As a process change, this banner is taken out before the release is performed and replaced afterwards.

**Comment by rhyshort** [comment]
I've opened a PR which adds a line to the README for the sample to point to the latest code. There are a bunch of links at the top the main README these days, so I haven't done anything there to point to the latest release. Hopefully users reading the README will click on the java doc badges.

I think that should be enough for now, but we should keep track in case it proves to not be enough.

**Comment by rhyshort** [comment]
Its been around a month an half since merge the doc changes, there hasn't been any issues so far with confusion, closing.
