### ISSUE TITLE
Replication history for checkpoint documents

### ISSUE THREAD

**Issue by ricellis** [cloudant/sync-android#296]
During replication, the local and remote checkpoint documents should be compared to make sure the last sequence number contained in each matches before that sequence number is used as the starting point for reading the source database's change feed.

Both documents need to be checked, because otherwise one of the source or target databases my have been changed (e.g., deleted and recreated) in such a way that replication needs to restart before it can be carried out correctly.

This can cause problems if a checkpoint document is only written to one database or the other. Say a local checkpoint document is written, but because a device has gone offline the remote one cannot be written. In this case the local and remote checkpoint documents contain differing last sequence numbers, so the replication starts from 0 in the case of naively comparing just the last sequence numbers in the documents.

CouchDB implements a cleverer algorithm where a history of sequence numbers at replication time are maintained. This means that in the above situation it's possible for the oldest common sequence number to be found and the replication continued from there rather than having to reset completely.
1. Check if the replication code checks for matching sequence numbers in source and target. If not implement that check.
2. Start maintaining history in the checkpoint documents that we write to both ends of the replication process and implement the mechanism to find a latest common version.

**Comment by rhyshort** [comment]
The algorithm is outlined in the [CouchDB docs](http://docs.couchdb.org/en/master/replication/protocol.html#find-common-ancestry). It means there needs to be some modification of the format we use for the checkpoint doc and a way to gracefully handle that.

**Comment by zedherle** [comment]
@ricellis Hi, i have a similar issue in my setup. 

I use the latest cloudant-sync lib. There are times, some documents does not replicated to my local tablet from a system which has couch db. 

When i checked, the sequence number in the system (source) from which i am pulling from has sequence number is way less than the target (my tablet) i am pulling to. 

I can't reset the sequence in the library too.. Trying to find an optimal way to fix this random issue. 

Do you suggest any?

**Comment by jjrodrig** [comment]
Hi @zedherle, I've been using this library since 2018 in different Android applications and I didn't notice a problem like this one. 

As far I know, If the target provides a not recognized seq number to CouchDB, the replication starts from the beginning. I had this effect when we performed a database swap for document purging. 

The enhancement described by this issue is an optimization that tries to avoid to start the replication from the begining in some cases.

**Comment by ricellis** [comment]
>the sequence number in the system (source) from which i am pulling from has sequence number is way less than the target (my tablet) i am pulling to

It is unclear to me exactly which sequence numbers you are comparing, but the local sync datastore keeps it's own sequnce IDs that are not related to the remote CouchDB sequnce numbers - they are not comparable with each other.

In sync-android for a pull replication a local checkpoint doc is consulted to identify the last sequence (of the remote) from where to resume the changes feed.

As @jjrodrig said the limitations described here mean a replication is more likely to start from the beginning when maybe it doesn't need to. So I doubt this is related to your problem unless your affected replications are actually still incomplete and haven't caught up yet and so it could look like e.g. recent changes are missing.

**Comment by zedherle** [comment]
Thank you @ricellis @jjrodrig for the response and help. 

_I have put some logs here_

1. When i start the replication from my tablet, the rep URL is as below,

`**https://url/somedb/_changes?feed=normal&seq_interval=1000&limit=1000&style=all_docs&since=162**
`
2. The result of this replication URL on couch DB 

`https://url/somedb/_changes?feed=normal&seq_interval=1000&limit=1000&style=all_docs&since=162
`
```
{"results":[
],
"last_seq":**162**}
```
Empty array :( i have not received anything. I was supposed to receive a new doc that i made there.
 
3. When i checked, the actual last sequence on CouchDB: 

`https://url/somedb/_changes
````
{"results":[
 /*many docs*/
]
"last_seq":**132**}
```

Here the source is 132 and the target is 162. 
I am trying to interpret here as "since=162 seq, there are no new docs to replicate, that is why i don't see them in the tablet.  (in-fact it had new docs there, which is missing currently)

Not sure, where i am making this wrong. Is there any hack to replicate everything without considering **since** parameter in the library?

**Comment by jjrodrig** [comment]
The question is why the server has a lower sequence than your tablet. Are you restoring the server to a previous state?

**Comment by zedherle** [comment]
Not restoring it. We push and then pull from the server as a part of replication. 

But there are times (which is obvious) in our case that both are disconnected and has new/updated data/document in both places. 

But since we are pushing from client to server, it should have updated the sequence there too right? 

What can go wrong in missing some documents while replicating from server to client?

**Comment by zedherle** [comment]
@ricellis @jjrodrig : we are using CouchDB v1.7.2 in the server.

**Comment by emlaver** [comment]
> But there are times (which is obvious) in our case that both are disconnected and has new/updated data/document in both places.
> 
> But since we are pushing from client to server, it should have updated the sequence there too right?

@zedherle Push and pull replication are completely independent and will maintain their own checkpoints and use independent seqs of each other. Also, as Rich mentioned in https://github.com/cloudant/sync-android/issues/296#issuecomment-921872959 the sequences on local and remote are not comparable.

The replication checkpoint ID name is made up of the source db name, target db name, and any provided options (e.g. filter, selector, etc)
With these details, here are two possibilities where the sequence number might get out-of-sync:
- target database on remote server is being re-created between replication jobs
- `target` database field is a proxy pointing to a database that may have been re-created or changed names between replications.  For example, `target=my.proxy.example` is a proxy that points to a database e.g. `db1.example`.  Then sometime later, the proxy points to `db2.example`. The two databases would have the same replication ID because the target URL matches, but there is no guarantee that `db1.example` and `db2.example` had the same sequences.

> What can go wrong in missing some documents while replicating from server to client?

During replication, `sync-android` will only write a checkpoint after a successful batch and then resume from there.  So if there's a disconnect during a replication, that batch is considered unsuccessful and the replication will resume using the latest checkpoint.  
If there's new changes on both the tablet and remote CouchDB, it’s possible there will be conflicts that need to be resolved.  You can implement the [`ConflictResolver` interface](https://github.com/cloudant/sync-android/blob/master/doc/conflicts.md#resolving-the-conflicts) to handle conflict management or resolve conflicts on the remote server.

Given that your situation is unrelated to this enhancement, please open a new issue if you have any additional comments or questions.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/sync-android/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
