### ISSUE TITLE
Authentication by cookie

### ISSUE THREAD

**Issue by emce** [cloudant/sync-android#36]
I've search all code, but there is no possibility to use custom http client or something similiar to override HttpRequests class - is tehere a possibility to make some kind of factory with HttpRequests as default profile?

**Comment by rhyshort** [comment]
Sorry for not keeping this ticket more up to date. With the release of 0.13.0 we introduced an [Interceptor API](https://github.com/cloudant/sync-android/blob/master/doc/interceptors.md) which includes the [CookieInterceptor](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/http/CookieInterceptor.java) class. You can use this interceptor with the `ReplicatorBuilder` class to create replications which use Cookie Authentication rather than basic auth.
