### ISSUE TITLE
Provide API for 'forceInsert()'

### ISSUE THREAD

**Issue by abhibana** [cloudant/sync-android#416]
In our project, we have the requirement to get documents from Server, and insert them to our local DB with same `revision` received from Server.

Use of `Replicator` and `filter functions`, is not suitable in our case.  Till now, we were using `forceInsert() ` method of `DatastoreImpl`. But later in the forum we got to know that, `DatastoreImpl` is not a public class to be used and `forceInsert()` was not supposed to be consumed by end user.

But for our project implementation, use of` forceInsert()` is very much crucial. So, we are requesting you to provide an **implementation** to access the same functionality of `forceInsert()`.

**Comment by ricellis** [comment]
As you have observed the `DatabaseImpl` and associated `forceInsert` were not intended as public API and have been [documented as "API Status: Private"](http://static.javadoc.io/com.cloudant/cloudant-sync-datastore-core/1.0.0/com/cloudant/sync/datastore/DatastoreImpl.html) since the API was set for version 1.0.0. The motivation for this was to reduce the complexity of the user facing API. Since the sync library is intended to perform the replication automatically between Cloudant and the device document store we aimed to hide the underlying complexity of the operations necessary for the replication and the device document store was not really designed for use with another replicator.

So whilst the sync library’s replicator needs access to `forceInsert` that operation does not need to be API for the normal use case. The force insertion of revisions may cause unexpected consequences or easily get messy with [conflicts](http://docs.couchdb.org/en/2.0.0/replication/conflicts.html). As a result it is not something that we would want to generally expose, for example, alongside the device document store’s other CRUD operations API. So we’ll need to carefully consider how it might be possible to satisfy this special case.

Since this is quite a departure from the typical golden path usage of the library I’d like to make sure that we understand the requirement properly. Could you elaborate on the use case a bit, for example, which variant of `forceInsert` are you currently using? Are there any other methods required for your use case?

**Comment by abhibana** [comment]
Currently we are using` forceInsert(final List<ForceInsertItem> items)` method do perform the Force Insert procedure. You can find the implementation [here](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/datastore/DatastoreImpl.java#L720). 

As of now, we don't want access to any other methods. Though we understand that **we aren't walking on the typical golden path usage of the library**, yet we don't have a choice.

In our requirement, **we want to insert a document with the revision that we receive from a server without setting up a replication between the server and the android client**. **On the server side, we're dealing with the Conflict managements**.

**Comment by ricellis** [comment]
I'm reluctant to start a cascade of exposing internal classes starting with the `ForceInsertItem` and all the classes associated with its constructor. I think it could be better to base the API on an existing public class like `DocumentRevision` or possibly a new sub-class of that e.g.

```java
forceInsert(DocumentRevision revision, List<String> ascendingOrderRevisionHistory);
```
or 
```java
forceInsert(DocumentRevisionWithHistory revision);
```

What is the starting point for the documents you are wanting to force insert? I assume you are receiving them as JSON from a request, but do you already deserialise them to some other Java type? Is the code you are using [this code block from sync-android-p2p](https://github.com/ibm-cds-labs/sync-android-p2p/blob/master/src/main/java/com/cloudant/p2p/listener/HttpListener.java#L349) or a similar refactoring of that?

It’s possible that the easiest to use method argument for this proposed API would be to accept the raw JSON of a document revision (that includes the `_revisions` property). e.g.
```java
forceInsert(String documentRevisionJson);
```

Does that fit with your use case or do you think another Java type would be more suitable?

**Comment by abhibana** [comment]
Both `forceInsert(DocumentRevision revision, List<String> ascendingOrderRevisionHistory);` and `forceInsert(DocumentRevisionWithHistory revision);` are equally applicable in our case. 

But, we're more familiar with first approach. Currently we are also doing the same while creating a `ForceInsertItem` with a `DocumentRevision` object and a `List<String> revisionHistory`.

Before doing the `forceInsert()`, we're not Deserialising the JSON response to any other Java type. So, in the response document we do have the `_revision` field. So, can you elaborate more on the use case of `forceInsert(String documentRevisionJson);` where our response document should contain `_revisions` property.

**Comment by ricellis** [comment]
The JSON that is typically used for this type of operation is a document with the `revisions` property, for example:
```javascript
{"_id":"exampledoc1",
"_rev":"4-51aa94e4b0ef37271082033bba52b850",
"_revisions":
    {"start":4,
      "ids": ["51aa94e4b0ef37271082033bba52b850",
             "f9fb951ca8dadec1459450156b2205cf",
             "617a372bba833d7acf3ccf2e7dece15a",
             "967a00dff5e02add41819138abb3284d"]
    },
// … other document properties
}
```

My thought was that by accepting that raw JSON content directly it would make the API easier to use. However, after considering it further I think it would be cumbersome for documents with attachments that were not pulled in-line because the attachment content would be separate from the JSON. That would mean exposing additional APIs to be able to insert and associate attachments. So using the existing `DocumentRevision` class, which already has attachment functionality probably makes more sense. 

I think it may be beneficial to follow the CouchDB `revs=true` parameter’s `_revisions` format more closely with the proposed API than the current `forceInsert` method does though to reduce the amount of JSON and revision ID manipulation that might be needed.

With that in mind I think something like this could be appropriate:
```java
    /**
     * <P>
     * Creates a new revision in the database with the specified revision history. This is
     * equivalent to inserting a revision with {@code new_edits: false}.
     * </P>
     * <P>
     * Note that the revisionsStart and revisionsIDs parameters describe the revision history of the
     * document revision being inserted. This history is equivalent to getting the document from
     * CouchDB with the {@code revs=true} parameter.
     * An example document retrieved with this _revisions history would be:
     * </P>
     * <pre>
     *
     * {@code
     * {"_id”:”exampledoc1”,
     * "_rev":"4-51aa94e4b0ef37271082033bba52b850",
     * "_revisions":
     *     {"start":4,
     *      "ids": [“51aa94e4b0ef37271082033bba52b850",
     *              "f9fb951ca8dadec1459450156b2205cf",
     *              "617a372bba833d7acf3ccf2e7dece15a",
     *              "967a00dff5e02add41819138abb3284d"]
     *     },
     *     ... // other document properties
     * }
     * }
     * </pre>
     * <P>
     * Example usage to insert this example document:
     * </P>
     * <pre>
     *
     * {@code
     *
     * DocumentRevision documentRevision = new DocumentRevision("exampledoc1",
     *     "4-51aa94e4b0ef37271082033bba52b850");
     * // set document content etc
     * documentRevision.setBody(...)
     * // set attachments
     *
     * documentStore.databaseWithAdvancedAPIs()
     *    .createWithHistory(documentRevision, 4, Arrays.asList(“51aa94e4b0ef37271082033bba52b850",
     *              "f9fb951ca8dadec1459450156b2205cf",
     *              "617a372bba833d7acf3ccf2e7dece15a",
     *              "967a00dff5e02add41819138abb3284d"))
     * }
     * </pre>
     *
     * @param documentRevision the revision of the document to create in the database
     * @param revisionsStart   the generation ID of the revision being inserted, for
     *                         example obtained from the {@code start} property of
     *                         the {@code _revisions} property object of a document
     *                         obtained with {@code revs=true}
     * @param revisionsIDs     the sequence of revision IDs (excluding the generational prefix)
     *                         starting with the revision being inserted and progressing to the root
     *                         of the document, for example a list of the JSON array content of the
     *                         {@code ids} property of the {@code _revisions} property object of a
     *                         document obtained with {@code revs=true}
     * @throws DocumentException if there was an error inserting the revision or its attachments
     *                           into the database
     */
    void createWithHistory(DocumentRevision documentRevision, int revisionsStart, List<String>
            revisionsIDs) throws DocumentException;
```

So using that proposal with the earlier example the [sync-android p2p HttpListener](https://github.com/ibm-cds-labs/sync-android-p2p/blob/master/src/main/java/com/cloudant/p2p/listener/HttpListener.java#L366) code would become something like:

```java
for (Map<String, Object> doc : docs) {
  String docId = (String)doc.get("_id");
  String revId = (String)doc.get("_rev");
  Map<String, Object> revisionHistoryMap = (Map<String, Object>)doc.get("_revisions");
  int revStart = (Integer) revisionHistoryMap.get("start");
  List<String> revisionIds = (List<String>) revisionHistoryMap.get("ids");
  doc.remove("_revisions");
  doc.remove("_id");
  doc.remove("_rev");
  DocumentBody body = DocumentBodyFactory.create(doc);
  DocumentRevision revisionToInsert = new DocumentRevision(docId, revId);
  revisionToInsert.setBody(body);
  // Set attachments if necessary
  try {
    ds.databaseWithAdvancedAPIs().createWithHistory(revisionToInsert, 
        revStart, revisionIds);
  } catch (DocumentException e) {
    // throw
  }
}
```

What do you think?

**Comment by ricellis** [comment]
I've gone with that approach in this prototype branch https://github.com/cloudant/sync-android/tree/416-prototype
