### ISSUE TITLE
Saving Revision in Cloudant Sync as an ordered LinkedHashMap, but not keeping the field's order in the server database (Cloudant), after replication

### ISSUE THREAD

**Issue by RHV044** [cloudant/sync-android#515]
I have already post this issue on StackOverflow:
http://stackoverflow.com/questions/42729853/saving-revision-in-cloudant-sync-as-an-ordered-linkedhashmap-but-not-keeping-th

Does anyone know if cloudant sync keeps the order of the LinkedHashTable when saving the revision and during replication? 

Thanks!

**Comment by ricellis** [comment]
No, the order isn't preserved as outlined in the [StackOverflow answer](http://stackoverflow.com/a/42752193/5825497).

Is this causing a particular problem for you?
It would be interesting even though I don't think the library is doing anything wrong since the RFC7159 JSON specification states in the [introduction](https://tools.ietf.org/html/rfc7159#section-1):
> An object is an unordered collection ...

and continues in the description of [objects](https://tools.ietf.org/html/rfc7159#section-4):
> Implementations whose behavior does not depend on member ordering will be interoperable in the sense that they will not be affected by these differences.
