### ISSUE TITLE
example of geo query in android

### ISSUE THREAD

**Issue by repoiso** [cloudant/sync-android#535]
dear all,

i understand the query and it's working perfectly for me.
but how can i use to get geo query? didn't found any example code.

what i want to do , is getting query result (will always be one)
that i give geo point, lan, lat and radius and it will give me in result the document id (_id)
or will not give me anything if not found.

i trying to do this over a month with no success.

**Comment by ricellis** [comment]
There are no specific geo query APIs built into sync-android (i.e. equivalent to Cloudant's `_geo` query endpoint).

However, it is possible to query lat/lon values in a document using a standard Cloudant query syntax selector. Of course care needs to be taking with wrapping around at `180` and `+`/`-` values and the appropriate `$gt` and `$lt` operators. It is also easier with a rectangular boundary rather than a radius.

For example to get all the document IDs between 50º and 52º and -1º and 1º you could do something like:
```java
Query q = ds.query();
List<Map<String, Object>> bounds = new ArrayList<>();
bounds.add(Collections.singletonMap("lat", Collections.singletonMap("$gt", 50)));
bounds.add(Collections.singletonMap("lat", Collections.singletonMap("$lt", 52)));
bounds.add(Collections.singletonMap("lon", Collections.singletonMap("$gt", -1)));
bounds.add(Collections.singletonMap("lon", Collections.singletonMap("$lt", 1)));
Map<String, Object> selector = Collections.singletonMap("$and", bounds);

QueryResult result = q.find(selector);
System.out.println(result.documentIds());
```

For performance reasons you should also make sure you create an index for your documents using the lat/long e.g.
```java
List<FieldSort> fields = new ArrayList<>();
fields.add(new FieldSort("lat"));
fields.add(new FieldSort("lon"));
q.createJsonIndex(fields, "myNamedCoordinateIndex");
```
