### ISSUE TITLE
In replication, how to configure the filter parameters？

### ISSUE THREAD

**Issue by LiuQhahah** [cloudant/sync-android#556]
Please include the following information in your ticket.

- sync-android version(s) that are affected by this issue. 2.0.2
- sync-android artifact you are using
    - [ ] cloudant-sync-datastore-android  1
    - [ ] cloudant-sync-datastore-android-encryption
    - [ ] cloudant-sync-datastore-javase
- Android or Java version (including vendor and platform). android
- A small code sample that demonstrates the issue.
```
Map<String,String> parameterrs = new HashMap<String,String>();
        parameterrs.put("key","value");
        PullFilter filter = new PullFilter("filterDoc/filterFunctionName",parameterrs);

        mPullReplicator = ReplicatorBuilder
                .pull()
                .to(mDocumentStore)
                .from(uri)
                .filter(filter)
                .build();
```

```
{
  "_id": "employee123",
  "_rev": "1-40fe9f5301fd4c7d09841bca90a2d0ea",
  "department": 23,
  "name": "Bob Smith",
  "title": "Developer",
  "address": {
    "street": "123 Main St.",
    "city": "Boston",
    "state": "MA"
  },
  "skills": [
    "Cloundant",
    "NoSQL",
    "JSON"
  ],
  "active_employee": true
}
```

what are the meaning of  "key","value"，“filterDoc”,"filterFunctinName"?   Can you give an example by the above data?

**Comment by emlaver** [comment]
Hi @LiuQhahah, the `key` and `value` are for any parameters required for the filter function.   
The `filterDoc` is the design document and the `filterFunctionName` is the name of the filter function.  
For example, let's say we have a test database that contains documents about animals:
```
{
  "_id": "giraffe",
  "max_weight": 1600,
  "class": "mammal",
  "diet": "herbivore"
}
```

We have this design document with filter function:
```
{
  "_id": "_design/animal",
  "filters": {
    "by_class": "function(doc, req) { if(doc.class && doc.class == req.query.class) { return true; } return false; }",
  }
}
```
Since the design doc ID is `_design/animal` and `by_class` is the filter function, we'd use `"animal/by_class"` as the `filterName`.   

Let's also say that some of the animal documents in this test database have the key/value pair `"class": "mammal"`.  If we want the filter results to only be animal documents where `class` equals `mammal`, we would add `"class, mammal"` to the `parameters` Java map.

This is the `PullFilter` we'd create for this example:
```
Map<String,String> parameters = new HashMap<String,String>();
        parameters("class", "mammal");
        PullFilter filter = new PullFilter("animal/by_class", parameters);
```

There are filter function examples with parameters in the [CouchDB Filter Functions](http://docs.couchdb.org/en/latest/ddocs/ddocs.html#filter-functions) documentation.

`PullFilter(filterName, parameters)` javadoc:
https://github.com/cloudant/sync-android/blob/877ed24208bc5ba707eee03ecbed038422ad7287/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/replication/PullFilter.java#L76-L97

**Comment by LiuQhahah** [comment]
Thanks!

**Comment by LiuQhahah** [comment]
How to limit the number of data in the process of Replicator?  I just want to download the first 100 data sorted by id

**Comment by emlaver** [comment]
@LiuQhahah There isn’t a way to do this with `sync-android` replication.  If you don’t need to keep a local replica of the database, you could use [java-cloudant](https://github.com/cloudant/java-cloudant)  to make a request to fetch the 100 documents.  Check out the `AllDocsRequestBuilder` in the [javadoc](http://www.javadoc.io/doc/com.cloudant/cloudant-client/2.10.0) for more information and examples.

**Comment by LiuQhahah** [comment]
Thanks!!
