### ISSUE TITLE
Quick start guide needs updating

### ISSUE THREAD

**Issue by rhyshort** [cloudant/sync-android#56]
The [quick start guide](https://github.com/cloudant/sync-android/blob/master/doc/android-qs.md) needs updating to inform users build tools version 19.1 and Gradle 2.1 is needed, Problem section probably needs updating and it may be a good idea to update the dashboard screen shorts too.

**Comment by tomblench** [comment]
I am in favour of deleting this. We don't have an equivalent in CDTDatastore and our documentation/README has matured a lot since when this was written. Also it goes through a lot of Cloudant specific things which are better explained elsewhere.

However, we also need to update our documentation for [the sample project](https://github.com/cloudant/sync-android/tree/master/sample/todo-sync), partly because it is out of date and partly because it references this guide.

**Comment by rhyshort** [comment]
I think deleting it is probably the best thing to do, lets focus on what we know best, the library, and leave the setting up cloudant etc to the cloudant docs team. :)

**Comment by tomblench** [comment]
Done in #310
