### ISSUE TITLE
How search field quick to improve performance ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/sync-android#564]
I have a document which contains thousands of fields.(As below)
![js](https://user-images.githubusercontent.com/11150958/34303439-23b26376-e757-11e7-9156-c528e883e616.PNG)

Now I want to perform following searches.
1.When a user writes "a" the program suggests all the fields(`brandName`) in a document start with alphabets "a" & when a user writes "ab" the program search and suggest the all the fields (`brandName`) which start with "ab".

**Comment by emlaver** [comment]
Hi @ZaheerUdDeen, can you share the search index you created and the search query code you're using?
If you haven't created a search index, please take look at the [Cloudant docs on Search](https://console.bluemix.net/docs/services/Cloudant/api/search.html#search).
Also, there are query examples in `com.cloudant.client.api.Search` in our [documentation](http://www.javadoc.io/doc/com.cloudant/cloudant-client/2.11.0).

**Comment by ricellis** [comment]
The links @emlaver suggested are for `cloudant-client` (i.e. java-cloudant) and searching directly on the Cloudant database. I'm guessing since this issue is raised against sync-android you actually want to search against the on-device database.

I suggest you look at the [query documentation](https://github.com/cloudant/sync-android/blob/master/doc/query.md) which is how you search the on device database. For good performance you need to create indexes.
