### ISSUE TITLE
Can we update the database rather than create the new one?

### ISSUE THREAD

**Issue by asimwaleed** [cloudant/sync-android#609]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

I just wanted to know somethings which you didn't mentioned in the doc.

### 2. What you expected to happen
Can we only update the database  when the application start very first time rather than create the new one? If yes can you guide me? because i didn't find any where in the doc

### 3. What actually happened
Create the new database when the app open very first time.
## Environment details

Android 8.0 oreo

**Comment by ricellis** [comment]
As per the [documentation](https://www.javadoc.io/static/com.cloudant/cloudant-sync-datastore-core/2.4.1/com/cloudant/sync/documentstore/DocumentStore.html#getInstance-java.io.File-) when calling `DocumentStore.getInstance(java.io.File location)` if a directory of database files already exists at the location then an existing instance will be returned, otherwise a new one will be created at the specified location.

So whether you get a new or existing depends on the directory path you provide and whether you previously made a database there.

**Comment by asimwaleed** [comment]
If the app is newly installed then there will be no DB at the specified path so can we install our app with predefined db or every time it will create new one if the app is newly installed?

**Comment by ricellis** [comment]
The expected approach is to populate the new database via replication from the server.

**Comment by asimwaleed** [comment]
can you send me the exact point in the documentation (if available in .md file) how can i achieve this?

**Comment by ricellis** [comment]
https://github.com/cloudant/sync-android/blob/master/doc/replication.md

**Comment by ricellis** [comment]
You'll want to do a [pull replication](https://www.javadoc.io/static/com.cloudant/cloudant-sync-datastore-core/2.4.1/com/cloudant/sync/replication/ReplicatorBuilder.html#pull--) from your Cloudant remote to your local document store.
